### ISSUE TITLE
I have error when running script and m3u file not created

### ISSUE THREAD

**Issue by vlad36N** [yohaybn/HA_ustvgo_sensor#2]
Hi,

I did following all instruction and code same as yours:
I have error when running script and m3u file not created:
Logger: homeassistant.components.script.cast_ustvgo
Source: helpers/script.py:1382
Integration: Script (documentation, issues)
First occurred: 11:21:37 AM (1 occurrences)
Last logged: 11:21:37 AM

Cast Ustvgo: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'sensor' is undefined

Using:
System Health

version: core-2021.12.10
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.63-v8
arch: aarch64
timezone: America/New_York

GitHub API: ok
Github API Calls Remaining: 5000
Installed Version: 1.20.0
Stage: running
Available Repositories: 1024
Downloaded Repositories: 29

host_os: Home Assistant OS 7.2
update_channel: stable
supervisor_version: supervisor-2021.12.2
docker_version: 20.10.9
disk_total: 228.5 GB
disk_used: 12.1 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok

![m3u](https://user-images.githubusercontent.com/30022288/151409284-d5d3a91c-cadd-4122-8c41-e995a91bd3bc.png)

**Comment by yohaybn** [comment]
Thank you for inform me.
I fixed it- there was some changes in ustvgo so I adopted the changes from https://github.com/benmoose39/ustvgo_to_m3u/blob/main/scripts/ustvgo_m3ugrabber.py
some of the channels that required VPN will not work now...
